---
services:
- type: web
  name: mcp
  runtime: node
  buildCommand: echo "No build required"
  startCommand: npx @typingmind/mcp vFN0rlGzmFuWiJwvKxCVA
  envVars:
  - key: AUTH_TOKEN
    value: "vFN0rlGzmFuWiJwvKxCVA"
  - key: REDIS_URL
    fromService:
      name: mcp-kv
      type: keyvalue
      property: connectionString
- type: keyvalue
  name: mcp-kv
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
