---
services:
- type: web
  name: mcp
  runtime: docker
  dockerfilePath: ./Dockerfile
  healthCheckPath: /health
  envVars:
  - key: AUTH_TOKEN
    sync: false
  - key: RENDER_API_KEY
    sync: false
  - key: REDIS_URL
    fromService:
      name: mcp-kv
      type: keyvalue
      property: connectionString
- type: keyvalue
  name: mcp-kv
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
