---
services:
- type: web
  name: mcp
  runtime: node
  buildCommand: npm install --production
  startCommand: node server.js
  envVars:
  - key: AUTH_TOKEN
    value: "72RW2Yop1JPfTCcpZOnxb"
  - key: MCP_PORT
    value: "8080"
  - key: MCP_HOST
    value: "0.0.0.0"
  - key: REDIS_URL
    fromService:
      name: mcp-kv
      type: keyvalue
      property: connectionString
- type: keyvalue
  name: mcp-kv
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
