name: Deploy to Render

on:
  push:
    branches:
      - main
      - genspark_ai_developer
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: '1.23'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Install dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build binary
      run: go build -v -o render-mcp-server main.go
    
    - name: Check binary
      run: ./render-mcp-server --version || true

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: render-mcp-server:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-notification:
    runs-on: ubuntu-latest
    needs: [test, docker-build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/genspark_ai_developer')
    steps:
    - name: Deployment Notice
      run: |
        echo "✅ Code is ready for deployment to Render"
        echo "Render will automatically deploy if auto-deploy is enabled"
        echo "Or manually trigger deployment from Render dashboard"